#!/bin/bash
curl -v \
-H "Content-Type: application/logplex-1" \
-H "Logplex-Msg-Count: 1" \
-d "116 <134>1 2012-12-10T03:00:48.123456Z erlang t.63982392-b768-426b-90a9-b74de23de322 console.1 - - Logsplat test message 1" \
http://local:password@10.5.0.4:8601/logs

# echo 1 | /home/vagrant/Development/go/src/github.com/heroku/log-shuttle/.docker_build/log-shuttle -logs-url=http://token:t.63982392-b768-426b-90a9-b74de23de322@10.5.0.4:8601/logs -appname appname -hostname hostname -procid procid
